/**
 * Synapse Dynamic API Mocking & Synthetic Response Generation Engine
 */

export class MockEngineService {
  /**
   * Synthesize realistic mock data matching OpenAPI schema
   */
  generateMockData(schema: Record<string, any>): any {
    if (!schema) return {};

    switch (schema.type) {
      case 'string':
        if (schema.format === 'date-time') return new Date().toISOString();
        if (schema.format === 'email') return 'developer@synapse.io';
        if (schema.format === 'uuid') return 'syn_' + Math.random().toString(36).substring(2, 12);
        if (schema.enum && schema.enum.length > 0) return schema.enum[0];
        return schema.example || schema.default || 'synapse_sample_string';

      case 'integer':
      case 'number':
        return schema.example || schema.default || Math.floor(Math.random() * 100) + 1;

      case 'boolean':
        return schema.example !== undefined ? schema.example : true;

      case 'array':
        const itemSchema = schema.items || { type: 'string' };
        return [
          this.generateMockData(itemSchema),
          this.generateMockData(itemSchema)
        ];

      case 'object':
      default:
        const result: Record<string, any> = {};
        if (schema.properties) {
          for (const [propName, propSchema] of Object.entries(schema.properties)) {
            result[propName] = this.generateMockData(propSchema as Record<string, any>);
          }
        }
        return result;
    }
  }

  /**
   * Produce mock HTTP response for an endpoint definition
   */
  getMockResponse(endpoint: { mockResponse?: any; responses?: any }): { status: number; body: any; headers: Record<string, string> } {
    if (endpoint.mockResponse) {
      return {
        status: 200,
        body: endpoint.mockResponse,
        headers: { 'Content-Type': 'application/json', 'X-Synapse-Mock': 'true' }
      };
    }

    if (endpoint.responses && endpoint.responses['200']?.schema) {
      const body = this.generateMockData(endpoint.responses['200'].schema);
      return {
        status: 200,
        body,
        headers: { 'Content-Type': 'application/json', 'X-Synapse-Mock': 'synthetic' }
      };
    }

    return {
      status: 200,
      body: { message: 'Mock response generated by Synapse Engine', timestamp: new Date().toISOString() },
      headers: { 'Content-Type': 'application/json', 'X-Synapse-Mock': 'fallback' }
    };
  }
}
